# Site settings
title: Bryan Chica
description: Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000"

# User settings
username: Bryan Chica
user_description: I'm a System Administrator living in Los Angeles, CA and I want to shape a digital world where individuals and organizations achieve their greatest ambitions, paving the way for exploration and creation without fear-allowing people to achieve more
user_title: Systems Admin
email: bryan.chica@outlook.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: bryan.chica
github_username:  chica-94
# medium_username: lorem_ipsum
medium_url: "./assets/Resume_Bryan_Chica.pdf"
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
